name: Continuous integration

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            script: ubuntu.sh
          - os: windows-latest
            script: windows.bat
          - os: macos-latest
            script: darwin.sh
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true


    - name: Build and test
      run: ./cicd/${{ matrix.script }} test
